apiVersion: v1
kind: Secret
metadata:
  name:  my-pg-exporter-prometheus-postgres-exporter
  labels:
    app: {{ template "prometheus-postgres-exporter.name" . }}
    chart: {{ template "prometheus-postgres-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  data_source_name: {{ .Values.dss | b64enc | quote }}